#:kivy 1.0
BoxLayout:
    orientation:'vertical'
    GridLayout:
        rows:3
        col:2
        padding : 10
        TextInput:
            size_hint: 1, .2
            text: 'hello'
        Image:
            source:'arz.png'
        TextInput:
            text: 'hello'
        Image:
            source:'arz.png'
        TextInput:
            text: 'hello'
        Image:
            source:'arz.png'

    Button:
        size_hint: 1, .2
        text: 'Command'


    GridLayout:
        rows:3
        col:2
        Label:
            text: '213'
        Image:
            source:'arz.png'
        Label:
            text: '213'
        Image:
            source:'arz.png'
        Label:
            text: '213'
        Image:
            source:'arz.png'
