<CustButton@Button>:
    font_size: 32
    color: 0, 0, 0, 1
    size : 150,50
    background_normal: ''
    background_down : 'arz.png'
    background_color : .88, .88, .88, 1

    <CustomWidget>:
        CustButton:
            text: 'random'
            pos : root.x, 200

        CustomButton:
            text: 'hello'
            pos : 200, root.y

        CustomButton:
            text: 'go'
            pos : 400, 200
